# mkdocs.yml
site_name: Webapp33
site_url: https://sites.uab.edu/periop-datascience/
repo_url: https://github.com/uabperiopai
nav:
  - Home: index.md
  - 'Webapp33':
    - Streamlit Interface: 'Webapp33/sample_handler.md'
    - User Interface: 'Webapp33_streamlit_app.md'
    - Example: 'Webapp33/utils/utils_example.md'
  - 'Webapp33_config':
    - Config: 'Webapp33_config/config.md'

  - llm_utils: '!include ./llm_utils/mkdocs.yml'

theme:
  name: readthedocs
plugins:
  - search
  - monorepo:
      submodules:
        - path: llm_utils
          repo_url: ''
  - mkdocstrings:
      handlers:
        python:
          paths: ['Webapp33', 'Webapp33_config', user_interface, llm_utils]  # search packages in these folders
watch:
  - .  # reload docs for any file changes
use_directory_urls: false